# Integrals_eig_bruteforce.py
# Eigenvalue computation for matrices generated by Iee_matrix_bruteforce_generate.py
import os
import glob
import numpy as np
import pickle
import math
from scipy.sparse import csr_matrix, diags
from scipy.sparse.linalg import eigsh, eigs
from matplotlib import pyplot as plt
from matplotlib.colors import TwoSlopeNorm

# Configuration
ms = [0, 1, 2, 3, 4, 5, 6, 7, 8]#,9,10,11,12,13,14,15,16,18,19,20]#[0, 1, 2, 3, 4, 5, 6, 7, 8]
k = 0  # Figure-1 style (no "-a2" files)

# PATCH: allow radial structure in each angular mode (critical for T^4 odd-m asymptotics)
RADIAL_BASIS_K = 6          # number of radial powers (k=0..K-1); 6–10 usually enough
RADIAL_SIGMA_P_MULT = 3.0   # sets Gaussian envelope width in p around p=1

# PATCH: do NOT add an absolute diagonal regularization when chasing tiny low-T rates.
# If you need stabilization, use a RELATIVE regularization tied to matrix scale.
REG_ABS = 0.0

# --- Mode reporting flags ---
# Report conserved modes as m=0 (density) and m=1 (momentum)
REPORT_CONSERVED_M0_M1 = True
# Compute relaxing modes separately as m0r and m1r
COMPUTE_M0_RELAX = True
COMPUTE_M1_RELAX = True
M0_BASIS_ORDER = 8          # number of radial basis polynomials (increase for accuracy)
M0_PROJECT_OUT_ENERGY = True  # recommended: remove energy-like invariant too
M1_PROJECT_OUT_DENS = True    # recommended: remove density when computing m1r

plt.rcParams['text.usetex'] = False
plt.rcParams['font.family'] = 'serif'
plt.rcParams["legend.frameon"] = False

# Directory where bruteforce matrices are stored
MATRIX_DIR = r"D:\Рабочая папка\GitHub\electronic-kapitsa-waves\kryhin_levitov_2021\collision_integral_direct\Matrixes_bruteforce"#"D:\Рабочая папка\GitHub\electronic-kapitsa-waves\kryhin_levitov_2021\collision_integral_direct\Matrixes_bruteforce"#"collision_integral_direct/Matrixes_bruteforce"


def _theta_str(theta: float) -> str:
    """Format theta for filename matching."""
    return f"{theta:.10g}"


def Fourier_transform2(func, th_i, dV_th, m):
    """Fourier transform for angular mode m."""
    exp = np.cos(th_i * m)
    integ = func * exp
    return np.sum(integ)


def build_centered_lattice(Nmax: int):
    """Build centered momentum lattice indices (same as in generator)."""
    half = Nmax // 2
    ns = np.arange(-half, half, dtype=np.int32)
    nx, ny = np.meshgrid(ns, ns, indexing="ij")
    nx = nx.reshape(-1)
    ny = ny.reshape(-1)
    return nx, ny, half


def reconstruct_px_py(meta):
    """
    Reconstruct px, py for active states from metadata.
    Returns: px, py arrays for active states
    """
    Nmax = int(meta["Nmax"])
    dp = float(meta["dp"])
    half = int(meta["half"])
    shift_x = float(meta.get("shift_x", 0.0))
    shift_y = float(meta.get("shift_y", 0.0))
    active = meta["active"].astype(np.int32)
    
    # Reconstruct full lattice
    nx_full, ny_full, _ = build_centered_lattice(Nmax)
    
    # Get active states
    nx_active = nx_full[active]
    ny_active = ny_full[active]
    
    # Compute physical momenta
    px = dp * (nx_active.astype(np.float64) + shift_x)
    py = dp * (ny_active.astype(np.float64) + shift_y)
    
    return px, py


def reconstruct_momentum_grid(meta):
    """
    Reconstruct momentum grid for active states from metadata.
    Returns: p_i (magnitude), th_i (angle), dV_p (radial measure), dV_th (angular measure)
    
    Create angular bins similar to original: use uniform angular grid with ~100 points.
    """
    Nmax = int(meta["Nmax"])
    dp = float(meta["dp"])
    half = int(meta["half"])
    shift_x = float(meta.get("shift_x", 0.0))
    shift_y = float(meta.get("shift_y", 0.0))
    active = meta["active"].astype(np.int32)
    
    # Reconstruct full lattice
    nx_full, ny_full, _ = build_centered_lattice(Nmax)
    
    # Get active states
    nx_active = nx_full[active]
    ny_active = ny_full[active]
    
    # Compute physical momenta
    px = dp * (nx_active.astype(np.float64) + shift_x)
    py = dp * (ny_active.astype(np.float64) + shift_y)
    p_i = np.sqrt(px * px + py * py)
    th_i = np.arctan2(py, px)  # angle in [-pi, pi]
    
    # Radial measure: dp^2 for 2D (area element in momentum space)
    dV_p = dp * dp
    
    # Create angular bins: use uniform grid like original (N_th = 100)
    # But adjust to match the actual distribution of angles
    # PATCH: higher angular resolution improves reconstruction accuracy
    # (does not change matrices, only postprocessing). With finer dp and half-integer shift,
    # you can safely use more bins without throwing away resolution.
    n_theta_bins = 360  # Level-2: increased from 100; Level-3: use 720 for very smooth Fourier modes
    th_bins = np.linspace(-np.pi, np.pi, n_theta_bins + 1)
    th_centers = 0.5 * (th_bins[:-1] + th_bins[1:])
    
    # Assign each state to an angular bin
    th_indices = np.digitize(th_i, th_bins) - 1
    th_indices = np.clip(th_indices, 0, n_theta_bins - 1)
    
    # Compute angular measure: dV_th[i] = (number of states in bin i) * dp^2
    counts = np.bincount(th_indices, minlength=n_theta_bins)
    dV_th = counts * dV_p
    
    return p_i, th_i, dV_p, dV_th, th_centers, th_indices


def compute_angular_distribution(Ma, meta, p_i, th_i, th_indices, dV_p, dV_th, th_centers):
    """
    Compute angular distribution by applying collision operator to test functions.
    
    Original code: core[i] = eta^T I[:,:,i] eta for each angular mode i
    where I[:,:,i] is the collision operator matrix for angular mode i.
    
    For bruteforce matrix M (2D), we need to compute the equivalent:
    - The matrix I[:,:,i] represents the collision operator projected onto angular mode i
    - We compute: core[i] = sum over states j in angular bin i of (eta[j] * (M @ eta)[j])
    - This approximates eta^T I[:,:,i] eta by binning the result
    """
    # Test function: eta = sqrt(p * dV_p) for number conservation
    # This matches the original: eta = np.sqrt(p_i * dV_p)
    eta = np.sqrt(p_i * dV_p)
    
    # Apply collision operator: M @ eta
    # This gives the collision operator's action at each momentum state
    if isinstance(Ma, csr_matrix):
        M_eta = Ma.dot(eta)
    else:
        M_eta = Ma @ eta
    
    # Compute quadratic form per state: eta[j] * (M @ eta)[j]
    # This is the contribution from state j
    core_per_state = eta * M_eta
    
    # Bin by angular index to get core[i] for each angular bin i
    # This approximates eta^T I[:,:,i] eta by summing contributions from states in bin i
    n_theta_bins = len(th_centers)
    core = np.zeros(n_theta_bins)
    for j, th_idx in enumerate(th_indices):
        core[th_idx] += core_per_state[j]
    
    # Normalize: dist[i] = core[i] * sqrt(dV_th[0]) * sqrt(dV_th[i])
    # This matches the original: dist = core * np.sqrt(dV_th[0]) * np.sqrt(dV_th)
    dist = np.zeros(n_theta_bins)
    nonzero_mask = dV_th > 0
    if np.any(nonzero_mask):
        # Use first bin as reference (original uses dV_th[0])
        # If first bin is empty, use first nonzero bin
        ref_idx = 0
        if dV_th[0] == 0:
            ref_idx = np.where(nonzero_mask)[0][0] if np.any(nonzero_mask) else 0
        
        if dV_th[ref_idx] > 0:
            dist[nonzero_mask] = (core[nonzero_mask] * 
                                  np.sqrt(dV_th[ref_idx]) * 
                                  np.sqrt(dV_th[nonzero_mask]))
    
    return dist, th_centers, dV_th


def get_matrix_files(matrix_dir=MATRIX_DIR):
    """
    Get list of matrix files without loading them.
    Returns: list of (Theta, filename) tuples sorted by Theta
    """
    pattern = os.path.join(matrix_dir, "M_Iee_N*_dp*_T*.pkl")
    files = glob.glob(pattern)
    
    if not files:
        raise FileNotFoundError(f"No matrix files found in {matrix_dir}. Pattern: {pattern}")
    
    # Extract Theta from each file and sort
    files_with_theta = []
    for fname in files:
        try:
            # Load just metadata to get Theta
            with open(fname, 'rb') as fp:
                M_sparse, meta = pickle.load(fp)
            Theta = float(meta["Theta"])
            files_with_theta.append((Theta, fname))
        except Exception as e:
            print(f"Error reading {fname}: {e}", flush=True)
            continue
    
    # Sort by Theta
    files_with_theta.sort(key=lambda x: x[0])
    return files_with_theta


def load_single_matrix(fname):
    """
    Load a single matrix file.
    Returns: (matrix, meta) tuple
    """
    with open(fname, 'rb') as fp:
        M_sparse, meta = pickle.load(fp)
    
    Theta = float(meta["Theta"])
    
    # Keep matrix as-is (sparse or dense) - don't convert large sparse to dense
    # The compute function will handle it appropriately
    return M_sparse, meta


def compute_eigenvalue_from_eigenfunction(Ma, meta, eigenfunction, m):
    """
    Compute eigenvalue from eigenfunction using the Rayleigh quotient.
    
    For collision operator: -M v = gamma W v
    The eigenvalue is: gamma = (v^T (-M) v) / (v^T W v)
    """
    w_active = meta["w_active"].astype(np.float64)
    w_safe = np.clip(w_active, 1e-30, None)
    
    # Collision operator: -M v = gamma W v
    A = -Ma if isinstance(Ma, csr_matrix) else csr_matrix(-Ma)
    
    # Compute numerator: v^T A v
    Av = A.dot(eigenfunction)
    numerator = np.dot(eigenfunction, Av)
    
    # Compute denominator: v^T W v
    Wv = w_safe * eigenfunction
    denominator = np.dot(eigenfunction, Wv)
    
    if abs(denominator) > 1e-30:
        gamma = numerator / denominator
    else:
        gamma = 0.0
    
    return float(gamma)


def verify_asymptotics(Thetas, eigs, modes=(2, 3, 4, 0), low_max=5e-2, high_min=1.5):
    """
    Verify asymptotic scaling behavior of eigenvalues.
    
    For Gurzhi / Fermi-liquid (Θ ≪ 1): γ(Θ) ∝ Θ²  =>  γ(Θ)/Θ² plateaus
    For Planckian / Sachdev (Θ ≫ 1):   γ(Θ) ∝ Θ   =>  γ(Θ)/Θ plateaus
    
    Args:
        Thetas: list of temperatures
        eigs: dict mapping Theta -> dict mapping m -> eigenvalue
        modes: modes to verify (default: 2,3,4,0 - skip m=1 which is conserved momentum)
        low_max: maximum Theta for low-T window (default: 5e-2)
        high_min: minimum Theta for high-T window (default: 1.5)
    """
    Thetas = np.array(sorted(Thetas), dtype=float)
    
    def fit_slope(theta_mask, y):
        """Fit log(y) = a * log(Theta) + b, return slope a."""
        x = np.log(Thetas[theta_mask])
        z = np.log(y[theta_mask])
        a, b = np.polyfit(x, z, 1)  # z ~ a x + b
        return a, b
    
    print("\n" + "="*70)
    print("=== Asymptotic Scaling Verification ===")
    print("="*70)
    
    for m in modes:
        # Handle both integer modes (m=0,1,2,3,4,...) and string modes (dens, px, py)
        if isinstance(m, str):
            # String mode like "dens", "px", "py" (invariants)
            y = np.array([eigs[t].get(m, np.nan) for t in Thetas], dtype=float)
        else:
            # Integer mode
            y = np.array([eigs[t].get(m, np.nan) for t in Thetas], dtype=float)
        good = np.isfinite(y) & (y > 0)
        
        if good.sum() < 6:
            print(f"\n[m={m}] not enough positive points ({good.sum()} valid)")
            continue
        
        # local slope (central diff)
        tt = np.log(Thetas[good])
        yy = np.log(y[good])
        alpha = np.gradient(yy, tt)
        
        low = good & (Thetas <= low_max)
        high = good & (Thetas >= high_min)
        
        print(f"\n[m={m}]")
        if low.sum() >= 4:
            aL, _ = fit_slope(low, y)
            print(f"  low-T fit  (Theta <= {low_max:g}): slope a = {aL:.3f}  (target ~2)")
            # plateau check
            gamma_over_theta2 = y[low] / (Thetas[low]**2)
            print(f"  low-T plateau check: median(gamma/Theta^2) = {np.median(gamma_over_theta2):.3e}")
            print(f"                         std(gamma/Theta^2) = {np.std(gamma_over_theta2):.3e}")
        else:
            print(f"  low-T: not enough points ({low.sum()} points)")
        
        if high.sum() >= 4:
            aH, _ = fit_slope(high, y)
            print(f"  high-T fit (Theta >= {high_min:g}): slope a = {aH:.3f} (target ~1)")
            # plateau check
            gamma_over_theta = y[high] / Thetas[high]
            print(f"  high-T plateau check: median(gamma/Theta) = {np.median(gamma_over_theta):.3e}")
            print(f"                        std(gamma/Theta) = {np.std(gamma_over_theta):.3e}")
        else:
            print(f"  high-T: not enough points ({high.sum()} points)")
        
        # quick diagnostic: where alpha is near 2 or near 1
        print(f"  alpha(theta) range: [{alpha.min():.2f}, {alpha.max():.2f}]")
        print(f"  valid points: {good.sum()}/{len(Thetas)}")
    
    print("\n" + "="*70)


def main():
    print("=== Eigenvalue / angular-distribution postprocessing (bruteforce) ===", flush=True)
    
    # Get list of matrix files (without loading them)
    files_with_theta = get_matrix_files()
    Thetas = [theta for theta, _ in files_with_theta]
    print(f"Found {len(files_with_theta)} matrix files", flush=True)
    print(f"Thetas={Thetas}", flush=True)
    print()
    
    # Step 1: Compute eigenfunctions for each temperature (process one at a time)
    print("=== Step 1: Computing eigenfunctions for each temperature ===", flush=True)
    all_eigenfunctions = {}
    all_eigenvalues_from_funcs = {}
    all_invariants = {}
    all_extra = {}
    
    for Theta, fname in files_with_theta:
        print(f"\n[compute eigenfunctions] Theta={Theta:.6g}", flush=True)
        print(f"  Loading matrix from {os.path.basename(fname)}...", flush=True)
        
        # Load matrix for this temperature only
        Ma, meta = load_single_matrix(fname)
        print(f"  Matrix shape: {Ma.shape}, type: {type(Ma).__name__}", flush=True)
        
        # Compute eigenfunctions for angular modes
        eigenfunctions, eigenvalues, px, py, eigenfunctions_extra, eigenvalues_extra, invariants, extra = compute_eigenfunctions_by_mode(Ma, meta, ms=ms)
        
        # Store results (these are small compared to matrices)
        all_eigenfunctions[Theta] = eigenfunctions
        all_eigenvalues_from_funcs[Theta] = eigenvalues
        # Store invariants and extra modes separately
        all_invariants[Theta] = invariants
        all_extra[Theta] = extra
        
        # Skip eigenfunction plotting to save time - only compute eigenvalues
        # plot_eigenfunctions_by_mode(eigenfunctions, eigenvalues, px, py, Theta, ms=ms,
        #                            save_prefix=f"eigenfunction_mode_T{Theta:.10g}",
        #                            show_plot=True)
        
        # Free memory - delete matrix
        del Ma, meta
        import gc
        gc.collect()
    
    # Step 2: Extract eigenvalues from eigenfunctions and plot vs T
    print("\n=== Step 2: Extracting eigenvalues from eigenfunctions ===", flush=True)
    eigs = {}
    
    for Theta in Thetas:
        print(f"[extract eigenvalues] Theta={Theta:.6g}", flush=True)
        eigenfunctions = all_eigenfunctions[Theta]
        
        eigs[Theta] = {}
        for m in ms:
            if eigenfunctions.get(m) is not None:
                # Use eigenvalue computed from eigenfunction
                eigs[Theta][m] = all_eigenvalues_from_funcs[Theta][m]
            else:
                eigs[Theta][m] = 0.0
        
        # Add invariants and extra modes from separate storage
        if Theta in all_invariants:
            inv = all_invariants[Theta]
            eigs[Theta]["dens"] = inv.get("dens", np.nan)
            eigs[Theta]["px"] = inv.get("px", np.nan)
            eigs[Theta]["py"] = inv.get("py", np.nan)
            eigs[Theta]["eps"] = inv.get("eps", np.nan)
        if Theta in all_extra:
            ext = all_extra[Theta]
            eigs[Theta]["m0r"] = ext.get("m0r", np.nan)
            eigs[Theta]["m1r"] = ext.get("m1r", np.nan)
            eigs[Theta]["gamma_vx"] = ext.get("gamma_vx", np.nan)
            eigs[Theta]["gamma_vy"] = ext.get("gamma_vy", np.nan)
    
    # ---- Verify asymptotic scaling ----
    # Use m0r and m1r (relaxing modes) instead of m=0 and m=1 (conserved)
    verify_modes = [2, 3, 4]
    # Add m0r and m1r if they exist
    has_m0r = any("m0r" in eigs[t] for t in Thetas)
    has_m1r = any("m1r" in eigs[t] for t in Thetas)
    if has_m0r:
        verify_modes.append("m0r")
    if has_m1r:
        verify_modes.append("m1r")
    verify_asymptotics(Thetas, eigs, modes=verify_modes, low_max=5e-2, high_min=1.5)
    
    # ---- Plot eigenvalues as in original script (Figure-1 style) ----
    f10, ax10 = plt.subplots(figsize=(8*0.9, 6*0.9))
    
    for m in ms:
        y = []
        y0 = []
        for Theta in Thetas:
            y.append(eigs[Theta][m])
            if k == 0:
                # IMPORTANT: keep baseline as conserved density (=0),
                # even if we repurpose m0 to be an isotropic relaxation mode.
                y0.append(0.0)
            else:
                y0.append(eigs[Theta][1])
        
        power = 2  # same choices as original
        
        # Initialize arrays (fixes UnboundLocalError)
        log_thetas = np.array([])
        log_vals = np.array([])
        
        # Plot all modes except m=1 (momentum conserved => zero line is boring)
        if k == 0 and m != 1:
            # Filter out invalid values
            y_arr = np.array(y, dtype=float)
            y0_arr = np.array(y0, dtype=float)
            Thetas_arr = np.array(Thetas, dtype=float)
            valid = np.isfinite(y_arr) & np.isfinite(y0_arr) & ((y_arr - y0_arr) > 0)
            if np.any(valid):
                log_thetas = np.log(Thetas_arr[valid])
                log_vals = 3*np.log(2*np.pi) + np.log((y_arr[valid] - y0_arr[valid])/(Thetas_arr[valid]**power))
                # Only plot if we have enough points
                if log_vals.size > 6:
                    # Use dotted line for m=0 to make it stand out visually
                    ls = ":" if m == 0 else "-"
                    ax10.plot(log_thetas[6:], log_vals[6:],
                              label=f"m = {m}", linewidth=1.5, linestyle=ls)
        
        if log_vals.size > 0:
            print(f"m={m}", log_thetas[6:] if log_vals.size > 6 else log_thetas,
                  log_vals[6:] if log_vals.size > 6 else log_vals)
        else:
            print(f"m={m}: no positive points to plot")
    
    # m=1 dashed special line (as in original)
    if k == 0:
        m = 1
        y = []
        y0 = []
        for Theta in Thetas:
            y.append(eigs[Theta][m])
            # IMPORTANT: keep baseline as conserved density (=0),
            # even if we repurpose m0 to be an isotropic relaxation mode.
            y0.append(0.0)
        power = 2
        y_arr = np.array(y, dtype=float)
        y0_arr = np.array(y0, dtype=float)
        Thetas_arr = np.array(Thetas, dtype=float)
        
        # Initialize arrays (fixes UnboundLocalError)
        log_thetas = np.array([])
        log_vals = np.array([])
        
        valid = np.isfinite(y_arr) & np.isfinite(y0_arr) & ((y_arr - y0_arr) > 0)
        if np.any(valid):
            log_thetas = np.log(Thetas_arr[valid])
            log_vals = 3*np.log(2*np.pi) + np.log((y_arr[valid] - y0_arr[valid])/(Thetas_arr[valid]**power))
            if log_vals.size > 5:
                ax10.plot(log_thetas[5:], log_vals[5:],
                          label="m = 1", linestyle="--", linewidth=1.5, color="gray")
                print("m=1", log_thetas[5:], log_vals[5:])
        else:
            print("m=1: no positive points to plot")
    
    # Reference lines (same as original)
    x_ref = np.linspace(-4.7, -3.0, 100)
    y_center = (2.2 + (-3.0)) / 2
    x_center = -3.0
    
    # x_ref = np.linspace(-4.7, -3.0, 100)
    # y_ref_2 = 1.9 + 0.0 * (x_ref - x_center)
    # ax10.plot(x_ref, y_ref_2, 'r--', alpha=0.6, linewidth=1.5, label=r'$T^2$')
    
    # x_ref = np.linspace(-4.7, -3.0, 100)
    # y_ref_33 = 0.68 + 1.3 * (x_ref - x_center)
    # ax10.plot(x_ref, y_ref_33, 'b-.', alpha=0.6, linewidth=1.5, label=r'$T^{3.3}$')
    
    # x_ref = np.linspace(-4.5, -3, 100)
    # y_ref_39 = y_center + 1.9 * (x_ref - x_center)
    # ax10.plot(x_ref, y_ref_39, 'm:', alpha=0.6, linewidth=1.5, label=r'$T^{3.9}$')
    
    # x_ref = np.linspace(-4.7, -2.0, 100)
    # y_ref_4 = -3 + 2.0 * (x_ref - x_center)
    # ax10.plot(x_ref, y_ref_4, 'g:', alpha=0.6, linewidth=2, label=r'$T^4$')
    
    # ax10.set_xlim(-4.7, 0.5)
    # ax10.set_ylim(-3.0, 2.2)
    ax10.set_xlabel(r'Temperature, $\ln (T/T_F)$')
    ax10.set_ylabel(r'Eigenvalues, $\ln(\lambda_m T_F^2/T^2)$')
    ax10.legend()
    
    f10.tight_layout()
    # Save eigenvalue plot
    f10.savefig('./Eigenvals_bruteforce.png', dpi=300, bbox_inches='tight')
    print("Saved: ./Eigenvals_bruteforce.png", flush=True)
    
    # Save eigenvalues to CSV file for later recreation
    print("\n=== Saving eigenvalues to CSV file ===", flush=True)
    import csv
    
    csv_filename = './Eigenvals_bruteforce.csv'
    with open(csv_filename, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        
        # Header: T, m0, m1, m2, ..., dens, px, py, eps, m0r, m1r, gamma_vx, gamma_vy
        header = ['T'] + [f'm{m}' for m in ms] + ['dens', 'px', 'py', 'eps', 'm0r', 'm1r', 'gamma_vx', 'gamma_vy']
        writer.writerow(header)
        
        # Write data rows
        for Theta in Thetas:
            row = [Theta] + [eigs[Theta].get(m, 0.0) for m in ms]
            # Add invariants (computed via Rayleigh quotient)
            row.append(eigs[Theta].get("dens", np.nan))
            row.append(eigs[Theta].get("px", np.nan))
            row.append(eigs[Theta].get("py", np.nan))
            row.append(eigs[Theta].get("eps", np.nan))
            # Add relaxing modes and current diagnostics
            row.append(eigs[Theta].get("m0r", np.nan))
            row.append(eigs[Theta].get("m1r", np.nan))
            row.append(eigs[Theta].get("gamma_vx", np.nan))
            row.append(eigs[Theta].get("gamma_vy", np.nan))
            writer.writerow(row)
    
    print(f"Saved: {csv_filename}", flush=True)
    print(f"  Thetas: {len(Thetas)} values, range [{min(Thetas):.6g}, {max(Thetas):.6g}]", flush=True)
    print(f"  Modes: {ms}", flush=True)
    print(f"  Total rows: {len(Thetas)}", flush=True)
    
    plt.show()


def compute_eigenfunctions(Ma, meta, n_eigs=10):
    """
    Compute eigenvalues and eigenvectors of the collision operator.
    
    The collision operator is typically solved as a generalized eigenvalue problem:
    -M v = gamma W v, where W = diag(f(1-f)) is the weight matrix.
    
    Returns:
        eigenvalues: array of eigenvalues (decay rates)
        eigenvectors: array of eigenvectors (eigenfunctions) in active subspace
        px, py: momentum coordinates for active states
    """
    # Get weight matrix W = diag(f(1-f)) from metadata
    w_active = meta["w_active"].astype(np.float64)
    w_safe = np.clip(w_active, 1e-30, None)  # Avoid zeros
    
    # Build weight matrix
    W = diags(w_safe, 0, format="csr")
    
    # Collision operator: -M v = gamma W v
    # So we solve: (-M) v = gamma W v
    A = -Ma if isinstance(Ma, csr_matrix) else csr_matrix(-Ma)
    
    # Add tiny regularization to help convergence (if needed)
    n = A.shape[0]
    if REG_ABS > 0.0:
        A = A + diags([REG_ABS] * n, 0, format="csr")
    
    # Transform to symmetric problem: B = W^{-1/2} A W^{-1/2}
    # Then solve: B y = gamma y, and recover v = W^{-1/2} y
    w_inv_sqrt = 1.0 / np.sqrt(w_safe)
    Dinv_sqrt = diags(w_inv_sqrt, 0, format="csr")
    B = Dinv_sqrt @ A @ Dinv_sqrt
    
    # Check symmetry
    sym_err = np.abs((B - B.T).data).max() / (np.abs(B.data).max() + 1e-30) if B.nnz > 0 else 0.0
    
    n_eigs = min(n_eigs, n - 2)  # Can't compute more than n-1 eigenvalues
    
    if sym_err < 1e-8 and n_eigs > 0:
        # Use symmetric solver
        try:
            vals, y = eigsh(
                B,
                k=n_eigs,
                sigma=1e-10,
                which="LM",  # Largest magnitude (smallest decay rates)
                tol=1e-8,
                maxiter=20000
            )
            # Recover eigenvectors: v = W^{-1/2} y
            vecs = (Dinv_sqrt @ y).astype(np.float64)
        except Exception as e:
            print(f"Warning: eigsh failed ({e}), trying eigs...", flush=True)
            vals, vecs = eigs(
                A,
                M=W,
                k=n_eigs,
                sigma=1e-10,
                which="LM",
                tol=1e-8,
                maxiter=20000
            )
            vals = np.real(vals)
            vecs = np.real(vecs)
    else:
        # Non-symmetric fallback
        print(f"Warning: Matrix not symmetric (error={sym_err:.3e}), using non-symmetric solver", flush=True)
        vals, vecs = eigs(
            A,
            M=W,
            k=n_eigs,
            sigma=1e-10,
            which="LM",
            tol=1e-8,
            maxiter=20000
        )
        vals = np.real(vals)
        vecs = np.real(vecs)
    
    # Ensure real
    vals = np.real(vals)
    vecs = np.real(vecs)
    
    # Sort by eigenvalue (ascending = slowest decay first)
    order = np.argsort(vals)
    vals = vals[order]
    vecs = vecs[:, order]
    
    # Normalize in W-norm: v^T W v = 1
    for i in range(vecs.shape[1]):
        v = vecs[:, i]
        wv = w_safe * v
        norm_w = np.sqrt(np.dot(v, wv))
        if norm_w > 1e-30:
            vecs[:, i] = v / norm_w
    
    # Reconstruct px, py
    px, py = reconstruct_px_py(meta)
    
    return vals, vecs, px, py


def plot_eigenfunctions(vals, vecs, px, py, Theta, n_plot=6, save_prefix="eigenfunction"):
    """
    Plot eigenfunctions as 2D plots in (px, py) space.
    
    Args:
        vals: eigenvalues
        vecs: eigenvectors (columns)
        px, py: momentum coordinates
        Theta: temperature
        n_plot: number of eigenfunctions to plot
        save_prefix: prefix for saved files
    """
    n_plot = min(n_plot, vecs.shape[1])
    
    # Create figure with subplots
    n_cols = 3
    n_rows = (n_plot + n_cols - 1) // n_cols
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, 5*n_rows))
    # Ensure axes is always a 1D array
    if not isinstance(axes, np.ndarray):
        axes = np.array([axes])
    else:
        axes = axes.flatten()
    
    # Determine common color scale
    vmin_all = np.inf
    vmax_all = -np.inf
    for i in range(n_plot):
        v = vecs[:, i]
        vmin_all = min(vmin_all, v.min())
        vmax_all = max(vmax_all, v.max())
    
    # Use symmetric colormap centered at zero
    vmax_abs = max(abs(vmin_all), abs(vmax_all))
    vmin_plot = -vmax_abs
    vmax_plot = vmax_abs
    
    for i in range(n_plot):
        ax = axes[i]
        v = vecs[:, i]
        gamma = vals[i]
        
        # Create scatter plot colored by eigenfunction value
        scatter = ax.scatter(px, py, c=v, s=1, cmap='RdBu_r', 
                            vmin=vmin_plot, vmax=vmax_plot, alpha=0.6)
        
        ax.set_xlabel(r'$p_x$')
        ax.set_ylabel(r'$p_y$')
        ax.set_title(f'Eigenfunction {i+1}, γ={gamma:.6e}\nΘ={Theta:.6g}')
        ax.set_aspect('equal')
        ax.grid(True, alpha=0.3)
        
        # Add colorbar
        plt.colorbar(scatter, ax=ax, label='Eigenfunction value')
    
    # Hide unused subplots
    for i in range(n_plot, len(axes)):
        axes[i].set_visible(False)
    
    plt.tight_layout()
    
    # Save figure
    fname = f'{save_prefix}_T{Theta:.10g}.png'
    # plt.savefig(fname, dpi=150, bbox_inches='tight')
    print(f"Saved: {fname}", flush=True)
    # plt.show()
    plt.close()


def wdot(u, v, w):
    """Weighted inner product: u^T W v"""
    return float(np.dot(u, w * v))

def rayleigh_gamma(A, w_safe, v):
    """
    Compute generalized decay rate: gamma = (v^T A v)/(v^T W v)
    for generalized eigenproblem A v = gamma W v.
    """
    v = v.astype(np.float64, copy=False)
    Av = A.dot(v)
    num = float(np.dot(v, Av))
    den = float(np.dot(v, w_safe * v))
    if den <= 1e-300:
        return np.nan
    return num / den


def w_orthonormalize(vecs, w, remove_basis=None):
    """
    W-orthonormalize a list of vectors, optionally removing projection onto a basis.
    
    Args:
        vecs: list of vectors to orthonormalize
        w: weight array (diagonal of weight matrix)
        remove_basis: optional list of vectors to remove projection onto
    
    Returns:
        list of W-orthonormal vectors
    """
    basis = []
    for v in vecs:
        u = v.astype(np.float64).copy()
        # Remove projection onto remove_basis if provided
        if remove_basis is not None:
            for q in remove_basis:
                u -= wdot(q, u, w) * q
        # Remove projection onto previous basis vectors
        for q in basis:
            u -= wdot(q, u, w) * q
        # Normalize
        nrm = np.sqrt(max(wdot(u, u, w), 0.0))
        if nrm > 1e-30:
            basis.append(u / nrm)
    return basis


def band_velocity(px, py, meta):
    """
    Compute band velocity v = dε/dk for bilayer dispersion.
    Returns velocity components vx, vy in dimensionless units (scaled by 1/mu).
    """
    U_BAND = float(meta.get("U_band", meta.get("band_u", 10.0)))
    V_BAND = float(meta.get("v_band", meta.get("band_v", 1.0)))
    MU_BAND = float(meta.get("mu_band", meta.get("mu_f", 1.0)))
    
    k = np.sqrt(px*px + py*py)
    k_safe = np.maximum(k, 1e-300)
    
    denom = np.sqrt((V_BAND*k)**2 + U_BAND*U_BAND)
    dEdk = (V_BAND*V_BAND * k) / denom  # dε/dk (in energy units)
    
    # Velocity in dimensionless form: dEdk/mu
    dEdk_dim = dEdk / MU_BAND
    
    vx = dEdk_dim * px / k_safe
    vy = dEdk_dim * py / k_safe
    return vx, vy


def compute_eigenfunctions_by_mode(Ma, meta, ms=[0, 1, 2, 3, 4, 5, 6, 7, 8]):
    """
    Compute eigenfunctions for specific angular modes m on the Fermi ring.
    
    Uses harmonic projection to find eigenfunctions corresponding to each angular mode.
    
    Returns:
        eigenfunctions: dict mapping m -> eigenfunction vector
        eigenvalues: dict mapping m -> eigenvalue (decay rate)
        px, py: momentum coordinates
    """
    # Get weight matrix W = diag(f(1-f)) from metadata
    w_active = meta["w_active"].astype(np.float64)
    w_safe = np.clip(w_active, 1e-30, None)
    
    # Reconstruct px, py, and angles
    px, py = reconstruct_px_py(meta)
    theta = np.arctan2(py, px)
    P = np.sqrt(px * px + py * py)   # this is k
    
    # --- bilayer dispersion: ε(k) = √(v²k² + U²) - U ---
    # Use same naming as generator
    U_BAND = float(meta.get("U_band", meta.get("band_u", 10.0)))
    V_BAND = float(meta.get("v_band", meta.get("band_v", 1.0)))
    MU_BAND = float(meta.get("mu_band", meta.get("mu_f", 1.0)))
    kF = float(meta.get("kF", meta.get("p_f", np.sqrt(MU_BAND*(MU_BAND + 2.0*U_BAND))/max(V_BAND, 1e-12))))
    vF = float(meta.get("vF", meta.get("v_f", (V_BAND*V_BAND*kF)/max(MU_BAND+U_BAND, 1e-12))))
    
    # dimensionless energy: eps_dim = eps(k) / mu, so Fermi level is at eps_dim = 1
    eps = np.sqrt((V_BAND * P)**2 + U_BAND * U_BAND) - U_BAND
    eps_dim = eps / MU_BAND
    
    Theta = float(meta.get("Theta", 0.0))
    Theta_val = float(meta.get("Theta", 1.0))  # Use 1.0 as default for scaling
    dp = float(meta.get("dp", 0.0))
    
    # Print band parameters for diagnostics
    print(f"  [band] U={U_BAND} v={V_BAND} μ={MU_BAND}  kF={kF:.6f}  vF={vF:.6f}", flush=True)
    
    # Collision operator: -M v = gamma W v
    # Handle matrix conversion carefully to avoid memory issues
    if isinstance(Ma, csr_matrix):
        # Already sparse - just negate
        A = -Ma
    elif isinstance(Ma, np.ndarray):
        # Dense array - convert to sparse if large, otherwise keep dense
        if Ma.size > 1e8:  # Very large matrix
            # For very large dense matrices, convert to sparse first, then negate
            print(f"  [warning] Large dense matrix ({Ma.shape}), converting to sparse...", flush=True)
            Ma_sparse = csr_matrix(Ma)
            A = -Ma_sparse
            del Ma_sparse  # Free memory
        else:
            # Small enough to work with directly
            A = csr_matrix(-Ma)
    else:
        # Try to convert to sparse
        A = csr_matrix(-Ma)
    
    W = diags(w_safe, 0, format="csr")
    
    # Add tiny regularization (if needed)
    n = A.shape[0]
    if REG_ABS > 0.0:
        A = A + diags([REG_ABS] * n, 0, format="csr")
    
    # Sanity check: verify momentum conservation
    # Also check energy conservation quality (optional but informative)
    if n > 0:
        # Use physical eps for energy conservation check
        eps_phys = eps_dim * MU_BAND
        eps_norm = np.linalg.norm(eps_phys)
        if eps_norm > 1e-30:
            A_eps = A.dot(eps_phys)
            Ae = np.linalg.norm(A_eps) / eps_norm
            print(f"  [sanity] ||A eps||/||eps|| = {Ae:.6e}", flush=True)
        
        # Check current/velocity conservation (should be ~0 for parabolic, nonzero for non-parabolic)
        vx, vy = band_velocity(px, py, meta)
        vx_norm = np.linalg.norm(vx)
        vy_norm = np.linalg.norm(vy)
        if vx_norm > 1e-30:
            A_vx = A.dot(vx)
            Avx = np.linalg.norm(A_vx) / vx_norm
            print(f"  [sanity] ||A vx||/||vx|| = {Avx:.6e}", flush=True)
        if vy_norm > 1e-30:
            A_vy = A.dot(vy)
            Avy = np.linalg.norm(A_vy) / vy_norm
            print(f"  [sanity] ||A vy||/||vy|| = {Avy:.6e}", flush=True)
    
    # Sanity check: verify momentum conservation
    Apx_norm = np.linalg.norm(A.dot(px))
    px_norm = np.linalg.norm(px)
    Apy_norm = np.linalg.norm(A.dot(py))
    py_norm = np.linalg.norm(py)
    print(f"  [sanity] ||A px||/||px|| = {Apx_norm/(px_norm + 1e-30):.3e}")
    print(f"  [sanity] ||A py||/||py|| = {Apy_norm/(py_norm + 1e-30):.3e}")
    
    # --- Compute invariants using Rayleigh quotient ---
    dens_vec = np.ones(n, dtype=np.float64)
    eps_phys = eps_dim * MU_BAND  # physical energy
    
    gamma_dens = rayleigh_gamma(A, w_safe, dens_vec)
    gamma_px   = rayleigh_gamma(A, w_safe, px)
    gamma_py   = rayleigh_gamma(A, w_safe, py)
    gamma_eps  = rayleigh_gamma(A, w_safe, eps_phys)
    
    # Compute velocity/current decay rates (diagnostics for non-parabolic bands)
    vx, vy = band_velocity(px, py, meta)
    gamma_vx = rayleigh_gamma(A, w_safe, vx)
    gamma_vy = rayleigh_gamma(A, w_safe, vy)
    
    invariants = {
        "dens": gamma_dens,
        "px": gamma_px,
        "py": gamma_py,
        "eps": gamma_eps,
    }
    
    print(f"  [invariants] gamma_dens={gamma_dens:.6e}  gamma_px={gamma_px:.6e}  gamma_py={gamma_py:.6e}  gamma_eps={gamma_eps:.6e}", flush=True)
    print(f"  [current] gamma_vx={gamma_vx:.6e}  gamma_vy={gamma_vy:.6e}", flush=True)
    
    # Invariants: density and momentum should be treated carefully.
    # Density is always conserved; momentum corresponds to the m=1 sector.
    inv_vecs = [np.ones(n, dtype=np.float64), px.copy(), py.copy()]
    
    # W-orthonormalize invariants (density + px + py)
    inv_orth = []
    for v in inv_vecs:
        v_norm = v.copy()
        # Remove projection onto previous invariants
        for q in inv_orth:
            proj = wdot(q, v_norm, w_safe)
            v_norm = v_norm - proj * q
        # Normalize
        nrm = np.sqrt(max(wdot(v_norm, v_norm, w_safe), 0.0))
        if nrm > 1e-30:
            v_norm = v_norm / nrm
            inv_orth.append(v_norm)
    
    eigenfunctions = {}
    eigenvalues = {}
    eigenfunctions_extra = {}
    eigenvalues_extra = {}
    
    # Store conserved modes for later use
    dens_u = inv_orth[0] if len(inv_orth) > 0 else None
    px_u   = inv_orth[1] if len(inv_orth) > 1 else None
    py_u   = inv_orth[2] if len(inv_orth) > 2 else None
    
    # Initialize relaxing mode storage
    m0r_gamma = np.nan
    m0r_vec = None
    m1r_gamma = np.nan
    m1r_vec = None
    
    for m in ms:
        if m == 0:
            # --- (A) Compute relaxing isotropic mode (m0r) first ---
            if COMPUTE_M0_RELAX:
                # 1) build "remove" basis: density, and optionally energy-like mode
                remove = inv_orth[:1] if len(inv_orth) > 0 else None
                if M0_PROJECT_OUT_ENERGY:
                    ones = np.ones(n, dtype=np.float64)
                    # Use physical eps for energy projection
                    eps_phys = eps_dim * MU_BAND
                    mean_eps = wdot(ones, eps_phys, w_safe) / max(wdot(ones, ones, w_safe), 1e-300)
                    e_mode = (eps_phys - mean_eps).astype(np.float64)
                    e_orth = w_orthonormalize([e_mode], w_safe, remove_basis=remove)
                    if remove is None:
                        remove = e_orth
                    else:
                        remove = remove + e_orth

                # 2) build a radial (angle-independent) basis around the Fermi surface
                # Scale by Theta so basis stays O(1) across temperatures
                # Use dimensionless energy: eps_dim - 1 (Fermi level is at eps_dim = 1)
                Tscale = max(Theta_val, 1e-12)
                x = (eps_dim - 1.0) / Tscale
                basis_raw = [(x ** k).astype(np.float64) for k in range(1, int(M0_BASIS_ORDER) + 1)]

                U_list = w_orthonormalize(basis_raw, w_safe, remove_basis=remove)
                print(f"  [m0r] basis kept: {len(U_list)} out of {len(basis_raw)}")
                if len(U_list) > 0:
                    # 3) project operator and solve small eigenproblem
                    U = np.column_stack(U_list)
                    AU = A.dot(U)
                    C = U.T @ AU
                    C = 0.5 * (C + C.T)

                    evals, evecs = np.linalg.eigh(C)
                    evals = np.real(evals)
                    evals = evals[np.isfinite(evals)]
                    evals = evals[evals >= -1e-12]
                    if len(evals) > 0:
                        j = np.argmin(np.maximum(evals, 0.0))
                        m0r_gamma = float(max(evals[j], 0.0))
                        m0r_vec = U @ evecs[:, j]

                        # normalize in W-norm
                        nrm = np.sqrt(max(wdot(m0r_vec, m0r_vec, w_safe), 0.0))
                        if nrm > 1e-30:
                            m0r_vec = m0r_vec / nrm

                        print(f"  [m0r] isotropic relax: gamma={m0r_gamma:.6e}")
                    else:
                        print(f"  [m0r] No valid eigenvalues in radial subspace")
                else:
                    print(f"  [m0r] basis empty -> cannot compute relaxing mode")
            
            # --- (B) Report conserved mode as m=0 ---
            if REPORT_CONSERVED_M0_M1:
                eigenfunctions[m] = np.ones(n, dtype=np.float64)  # density
                eigenvalues[m] = 0.0
                print(f"  [m=0] density conserved: gamma=0")
            continue
        
        if m == 1:
            # --- (A) Compute relaxing dipole mode (m1r) first ---
            if COMPUTE_M1_RELAX:
                # Build remove basis: density (optional) + momentum (px, py)
                remove = []
                if M1_PROJECT_OUT_DENS:
                    remove.append(np.ones(n, dtype=np.float64))
                remove.append(px.copy())
                remove.append(py.copy())
                remove = w_orthonormalize(remove, w_safe)
                
                # Build m=1 radial basis with proper angular structure
                # Use radial envelope around kF with m=1 angular harmonics
                depsdk_dim = max(vF / MU_BAND, 1e-12)
                dk_th = Theta_val / depsdk_dim
                sigma_k = max(RADIAL_SIGMA_P_MULT * dk_th, 4.0 * dp, 1e-12)
                
                z = (P - kF) / sigma_k
                g = np.exp(-0.5 * z * z)
                
                basis = []
                for kk in range(int(RADIAL_BASIS_K)):
                    rk = z ** kk
                    basis.append(g * rk * np.cos(1 * theta))
                    basis.append(g * rk * np.sin(1 * theta))
                
                U_list = w_orthonormalize(basis, w_safe, remove_basis=remove if len(remove) > 0 else None)
                print(f"  [m1r] basis kept: {len(U_list)} out of {len(basis)}")
                
                if len(U_list) > 0:
                    # Project operator and solve
                    U = np.column_stack(U_list)
                    AU = A.dot(U)
                    C = U.T @ AU
                    C = 0.5 * (C + C.T)
                    
                    evals, evecs = np.linalg.eigh(C)
                    evals = np.real(evals)
                    evals = evals[np.isfinite(evals) & (evals >= -1e-12)]
                    
                    if len(evals) > 0:
                        j = np.argmin(np.maximum(evals, 0.0))
                        m1r_gamma = float(max(evals[j], 0.0))
                        m1r_vec = U @ evecs[:, j]
                        
                        nrm = np.sqrt(max(wdot(m1r_vec, m1r_vec, w_safe), 0.0))
                        if nrm > 1e-30:
                            m1r_vec /= nrm
                        
                        print(f"  [m1r] dipole relax: gamma={m1r_gamma:.6e}")
                    else:
                        print("  [m1r] dipole relax: No valid eigenvalues")
                else:
                    print("  [m1r] dipole relax: basis empty")
            
            # --- (B) Report conserved mode as m=1 ---
            if REPORT_CONSERVED_M0_M1:
                # Use px as representative conserved momentum direction
                eigenfunctions[m] = px.copy()
                eigenvalues[m] = 0.0
                print(f"  [m=1] momentum conserved: gamma=0")
            continue
        else:
            # PATCH: for m>=2, allow radial structure (P-k_F)^k * cos/sin(mθ).
            # This is crucial: odd-m T^4 asymptotics typically requires cancellations
            # that a pure angular harmonic (2D basis) cannot represent.
            remove = inv_orth[:1] if len(inv_orth) > 0 else None  # remove density only

            # Choose a radial envelope width in k around k_F.
            # Thermal radial width in k: dk_th = (Theta / depsdk_dim) where depsdk_dim = vF/mu
            # Also include dp so we don't make the envelope narrower than grid resolution.
            depsdk_dim = max(vF / MU_BAND, 1e-12)
            dk_th = (Theta / depsdk_dim)  # k-width corresponding to energy width Theta
            sigma_k = max(RADIAL_SIGMA_P_MULT * dk_th, 4.0 * dp, 1e-12)
            z = (P - kF) / sigma_k
            g = np.exp(-0.5 * z * z)

            basis = []
            # Use powers of (P-k_F) (scaled by sigma_p) for numerical conditioning
            for kk in range(int(RADIAL_BASIS_K)):
                rk = (z ** kk)
                basis.append(g * rk * np.cos(m * theta))
                basis.append(g * rk * np.sin(m * theta))

            U_list = w_orthonormalize(basis, w_safe, remove_basis=remove)
        
        if len(U_list) == 0:
            print(f"  [m={m}] No valid basis, skipping")
            eigenfunctions[m] = None
            eigenvalues[m] = np.nan
            continue
        
        # Project operator onto basis: C = U^T A U
        U = np.column_stack(U_list)
        AU = A.dot(U)
        C = U.T @ AU
        C = 0.5 * (C + C.T)  # Symmetrize
        
        # Solve eigenvalue problem in basis
        evals, evecs = np.linalg.eigh(C)
        evals = np.real(evals)
        evals = evals[np.isfinite(evals) & (evals >= -1e-12)]
        
        if len(evals) == 0:
            print(f"  [m={m}] No valid eigenvalues")
            eigenfunctions[m] = None
            eigenvalues[m] = np.nan
            continue
        
        # Choose smallest non-negative eigenvalue (slowest decay in this subspace)
        j = np.argmin(np.maximum(evals, 0.0))
        gamma = float(max(evals[j], 0.0))
        u = U @ evecs[:, j]
        
        # Normalize in W-norm
        nrm = np.sqrt(max(wdot(u, u, w_safe), 0.0))
        if nrm > 1e-30:
            u = u / nrm
        
        # Optional: make m=1 plot stable by aligning with +px if it's that mode
        eigenfunctions[m] = u
        eigenvalues[m] = gamma
        
        print(f"  [m={m}] gamma={gamma:.6e}")
    
    # Store relaxing modes in extra dict
    extra = {
        "m0r": m0r_gamma,
        "m1r": m1r_gamma,
        "gamma_vx": gamma_vx,
        "gamma_vy": gamma_vy,
    }
    
    return eigenfunctions, eigenvalues, px, py, eigenfunctions_extra, eigenvalues_extra, invariants, extra


def plot_eigenfunctions_main(Theta=None, n_eigs=10, n_plot=6, use_angular_modes=True):
    """
    Main function to compute and plot eigenfunctions.
    
    Args:
        Theta: specific temperature to plot (if None, plot first available)
        n_eigs: number of eigenvalues to compute (if not using angular modes)
        n_plot: number of eigenfunctions to plot (if not using angular modes)
        use_angular_modes: if True, plot eigenfunctions for angular modes m=0,1,2,3,4,5
    """
    print("=== Computing and plotting eigenfunctions ===", flush=True)
    
    # Get matrix files
    files_with_theta = get_matrix_files()
    available_thetas = [theta for theta, _ in files_with_theta]
    
    if Theta is None:
        Theta = available_thetas[0]
        print(f"No Theta specified, using first available: {Theta:.6g}", flush=True)
    
    if Theta not in available_thetas:
        raise ValueError(f"Theta={Theta} not found. Available: {available_thetas}")
    
    # Find and load the specific matrix
    fname = next(fname for theta, fname in files_with_theta if theta == Theta)
    Ma, meta = load_single_matrix(fname)
    print(f"Computing eigenfunctions for Theta={Theta:.6g}, Nactive={len(meta['active'])}", flush=True)
    
    if use_angular_modes:
        # Compute eigenfunctions for specific angular modes
        ms = [0, 1, 2, 3, 4, 5, 6, 7, 8]
        eigenfunctions, eigenvalues, px, py, eigenfunctions_extra, eigenvalues_extra, invariants, extra = compute_eigenfunctions_by_mode(Ma, meta, ms=ms)
        
        # Plot eigenfunctions for each mode
        plot_eigenfunctions_by_mode(eigenfunctions, eigenvalues, px, py, Theta, ms=ms)
        
        # Return results (extra dict already created in compute_eigenfunctions_by_mode)
        return eigenfunctions, eigenvalues, px, py, eigenfunctions_extra, eigenvalues_extra, invariants, extra
    else:
        # Compute general eigenfunctions
        vals, vecs, px, py = compute_eigenfunctions(Ma, meta, n_eigs=n_eigs)
        
        print(f"Computed {len(vals)} eigenvalues:")
        print(f"  Range: γ_min = {vals[0]:.6e}, γ_max = {vals[-1]:.6e}")
        print(f"  First {min(5, len(vals))}: {vals[:min(5, len(vals))]}")
        
        # Plot eigenfunctions
        plot_eigenfunctions(vals, vecs, px, py, Theta, n_plot=n_plot)
        
        return vals, vecs, px, py


def plot_eigenfunctions_by_mode(eigenfunctions, eigenvalues, px, py, Theta, ms=[0, 1, 2, 3, 4, 5, 6, 7, 8], save_prefix="eigenfunction_mode", show_plot=True):
    """
    Plot eigenfunctions for specific angular modes m.
    
    Args:
        eigenfunctions: dict mapping m -> eigenfunction vector
        eigenvalues: dict mapping m -> eigenvalue
        px, py: momentum coordinates
        Theta: temperature
        ms: list of angular modes to plot
        save_prefix: prefix for saved files
        show_plot: whether to display the plot (default True)
    """
    # Filter out None eigenfunctions
    valid_ms = [m for m in ms if eigenfunctions.get(m) is not None]
    
    if len(valid_ms) == 0:
        print("No valid eigenfunctions to plot", flush=True)
        return
    
    # Create figure with subplots
    n_cols = 3
    n_rows = (len(valid_ms) + n_cols - 1) // n_cols
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, 5*n_rows))
    if not isinstance(axes, np.ndarray):
        axes = np.array([axes])
    else:
        axes = axes.flatten()
    
    # Determine common color scale
    vmin_all = np.inf
    vmax_all = -np.inf
    for m in valid_ms:
        v = eigenfunctions[m]
        vmin_all = min(vmin_all, v.min())
        vmax_all = max(vmax_all, v.max())
    
    # Use symmetric colormap centered at zero
    vmax_abs = max(abs(vmin_all), abs(vmax_all))
    vmin_plot = -vmax_abs
    vmax_plot = vmax_abs
    
    for idx, m in enumerate(valid_ms):
        ax = axes[idx]
        v = eigenfunctions[m]
        gamma = eigenvalues[m]
        
        # Create scatter plot colored by eigenfunction value
        scatter = ax.scatter(px, py, c=v, s=1, cmap='RdBu_r', 
                            vmin=vmin_plot, vmax=vmax_plot, alpha=0.6)
        
        ax.set_xlabel(r'$p_x$')
        ax.set_ylabel(r'$p_y$')
        ax.set_title(f'Angular mode m={m}, γ={gamma:.6e}\nΘ={Theta:.6g}')
        ax.set_aspect('equal')
        ax.grid(True, alpha=0.3)
        
        # Add colorbar
        plt.colorbar(scatter, ax=ax, label='Eigenfunction value')
    
    # Hide unused subplots
    for idx in range(len(valid_ms), len(axes)):
        axes[idx].set_visible(False)
    
    plt.tight_layout()
    
    # Save figure
    fname = f'{save_prefix}_T{Theta:.10g}.png'
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    print(f"Saved: {fname}", flush=True)
    # if show_plot:
        # plt.show()
    plt.close()


if __name__ == "__main__":
    # Main workflow: 
    # 1. Plot eigenfunctions for each temperature
    # 2. Extract eigenvalues from eigenfunctions and plot vs temperature
    main()

